module.exports  = {
    get root(){ return __dirname.replace(/(\/|\\)\w+$/g, '')},
    get mapp(){ return this.root+'/mapp'},
    get routes(){ return this.root+'/routes'},
    get routes_frontend(){ return this.routes+'/news'},
    get routes_backend(){ return this.routes+'/admin'},
    get routes_auth(){ return this.routes+'/auth'},
    get routes_mess(){ return this.routes+'/mess'},
    get libs(){return this.mapp+'/libs'},
    get views(){return this.mapp+'/views'},
    get views_admin(){return this.views+'/admin'},
    get views_news(){return this.views+'/news'},
    get views_auth(){return this.views+'/auth'},
    get views_mess(){return this.views+'/messenger'},
    get public(){return this.root+'/public'},
    rel_public: './',
    get files(){return this.public+'/files'},
    get rel_files(){return this.rel_public+'/files'},
    get model(){return this.mapp+'/model'},
    get middleware(){return this.mapp+'/middleware'},
    get middleware_frontend(){return this.middleware+'/frontend'},
    get schema(){return this.mapp+'/schema'},
    get validate(){return this.mapp+'/validate'},
    get helper(){return this.mapp+'/helper'},
    get helper_socketio(){return this.helper+'/socketio'},
    get config(){return this.mapp+'/config'},
    get config_display(){return this.config+'/display'},
}
